name: hyperliquid_dart
description: A Dart SDK for the Hyperliquid API.
version: 0.0.1
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dio: ^5.4.0
  json_annotation: ^4.8.1
  web3dart: ^2.7.3
  http: ^1.2.0 # web3dart needs http client
  logging: ^1.2.0
  msgpack_dart: ^1.0.1

dev_dependencies:
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  lints: ^3.0.0
  test: ^1.25.0
